name: Notification

on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT }}
          format: markdown
          message: |
            Новый PR от `${{ github.actor }}` в `${{ github.repository }}`.

            Ссылка на PR: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}
