name: Notification

on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
