name: reviewdog
on: [ pull_request ]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          fail_on_error: true
          reporter: github-pr-review
          stylelint_input: './src/**/*.{css,pcss}'
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          reporter: github-pr-review
          eslint_flags: '. --ext .ts,.tsx'
