name: Build and Deploy Storybook
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run storybook:build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

  notification:
    needs: build-and-deploy
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT }}
          format: markdown
          message: |
            Обновлен storybook: https://wildberries-tech.github.io/ui-react/
